language: c
compiler: gcc
script: mkmk init --config conprx.mkmk --debug --noisy && ./build.sh all run-tests
before_install: git submodule update --init --recursive
install: source ./tools/enter-devenv.sh
